
2/0
try:
    2/0
except Exception:
    print("error")

